### ISSUE TITLE
not working as expected using Android studio 3.0.1

### ISSUE THREAD

**Issue by FaisalJamil** [humblerookie/dimenify#10]
Using Android Studio 3.0.1 and following these steps,  
Generate for a specific dimen
Locate the dimens.xml file in the editor.
Move the cursor to the dimension and right click.
Select Generate -> Generate alternate dimens..
Insert the scale factors you want to use for conversion and click OK. (**Do not appear and hence no dimensions are generated**)

Generate for an entire file
Locate the dimens.xml file in the project view and right click.
Select 'Generate alternate dimens from file'.
Insert the scale factors for conversion and click OK. (**Scale factor appear this time, but empty dimens files are generated in respective resolution folders**)

**Comment by humblerookie** [comment]
Sorry about the delayed response. Thanks for pointing this out, will take a look today and let you know.

**Comment by humblerookie** [comment]
@FaisalJamil Is there any error log /trace showing up (bottom right corner on AS) while generating it? Could be a canary issue, I'm testing this on 3.1 Beta 1 and it works.
 Could you try it on the same?

**Comment by FaisalJamil** [comment]
Yeah, may be a Canary issue, as I am using it in my app. I’ll try and let you know. Thanks

On Feb 17, 2018, at 10:01 PM, Anvith Bhat <notifications@github.com<mailto:notifications@github.com>> wrote:


@FaisalJamil<https://github.com/faisaljamil> Is there any error log /trace showing up (bottom right corner on AS) while generating it? Could be a canary issue, I'm testing this on 3.1 Beta 1 and it works.
Could you try it on the same?

**Comment by humblerookie** [comment]
Could you confirm if you're still facing the issue on beta?

**Comment by humblerookie** [comment]
I'm closing this issue on the premise that this would be a canary issue, feel free to reopen in case otherwise.
