### ISSUE TITLE
Default values failed to prevent generate

### ISSUE THREAD

**Issue by tcqq** [humblerookie/dimenify#11]
I uncheck the checkbox of the red box, then I click on the OK button, but these values still generate.

![image](https://user-images.githubusercontent.com/10644057/41191133-83322066-6c1d-11e8-9030-61a79fd34c7e.png)
![image](https://user-images.githubusercontent.com/10644057/41191151-ac72f4dc-6c1d-11e8-971c-7642ee706414.png)

**Comment by humblerookie** [comment]
Issue patched in 
PR https://github.com/humblerookie/dimenify/pull/14
[Release](https://github.com/humblerookie/dimenify/releases/tag/v3.5)
