### ISSUE TITLE
Request to cancel the limit generation quantity

### ISSUE THREAD

**Issue by tcqq** [humblerookie/dimenify#12]
@humblerookie Request to cancel the limit generation quantity.
![image](https://user-images.githubusercontent.com/10644057/45732534-5ddb8900-bc0f-11e8-8308-a707f67ced9c.png)

**Comment by humblerookie** [comment]
@tcqq this was done more for facilitating the IntelliJ UI, out of curiosity how many buckets do you need?

**Comment by tcqq** [comment]
@humblerookie Yes, but now IntelliJ UI has no plugins that are better than this, so hope to change the number of buckets without limiting the number of buckets, so that the application can support more different screens, thank you.

**Comment by humblerookie** [comment]
https://github.com/humblerookie/dimenify/pull/13 should fix this. 
The plugin has been updated on IntelliJ repo. Raise a new issue in case you find any problems.

**Comment by tcqq** [comment]
Okay thank you.
