### ISSUE TITLE
String value in dimens file

### ISSUE THREAD

**Issue by amruta-pani** [humblerookie/dimenify#6]
The resultant dimens files for xhdpi, xxhdpi and so on contains , in some dp values like "76,8dp". This is not allowing to compile the program indicating a String value is not allowed. 

Why is there a , in some values? Even if it is to be considered as 76.8dp, there are values 10.8dp being generated at the same time. Even if I wanted to ignore  and replace ',' with a '.' , there are values 1,008.4dp.

**Comment by humblerookie** [comment]
Hey! thanks for pointing this out, I'll take a look at this . Could you help me out with your Timezone/Locale?

**Comment by amruta-pani** [comment]
+530, IST. What's that for by the way?

**Comment by humblerookie** [comment]
The DecimalFormat uses ',' as a decimal separator in some locales. This is not an issue for Indian zone though. Will check and make a release.

**Comment by amruta-pani** [comment]
That's what I too guessed on seeing it and went ahead to replace all , with
'.' until I came across a single value with both symbols. After doing some
math I understood that it is indeed a symbols issue. For eg, the resultant
value for xxxhdpi is supposed to be 1000.33dp while the plugin calc as
1.000,33dp.

**Comment by amruta-pani** [comment]
Nevertheless of the time zones, does android allows string values like , in
dimensions file

**Comment by humblerookie** [comment]
Apologies for this. The bug turns out in the MessageFormat class being used for the bulk conversion that prettyfies floating strings with a certain number of significant digits unless explicitly converted into String before hand. My bad nonetheless.

This issue has been addressed in #7  and [v3.2](https://plugins.jetbrains.com/plugin/download?updateId=36331) is available in plugin repository containing this fix.

**Comment by humblerookie** [comment]
@amruta-pani Just verifying whether the issue was resolved for you with the update?

**Comment by amruta-pani** [comment]
I'm sorry I couldn't check on that yet but I upgraded the plugin. Will keep
you posted

**Comment by amruta-pani** [comment]
Hi, I tested it and it's working. Thanks a lot.

I was wondering if I I could make a suggestion.
I think it would be more appropriate for this plugin to list out all the
possible densities available incl sw820 etc for the user to choose which
files to be generated. Also the multiplying factor too can be auto
populated as that is fixed value. Does this make sense?

Nevertheless this plugin saves a lot of effort in generating dimensions
files.

**Comment by humblerookie** [comment]
Thanks for suggesting those changes. But I have my reservations against them.

1) While it's feasible to list out all possible permutations of density, orientation, size etc. There are things that are troublesome for the said approach
-  It would be a massive list to scroll through, this with the added fact that developers only select a few buckets from those makes it an inconvenient UX. It's far more simpler to just key in the subjective density.
- Doing this would require a plugin update each time a new bucket/ permutation comes through lets say a xxxxhdpi tomorrow.

2) I thought of locking the scale ratios in the earlier version but I quickly realized designers have their own aesthetically appealing scale ratios that are not exactly consistent across icons, fonts and apps. The change however marginal (like 12sp in hdpi , would be 14sp for one designer for xhdpi but another designer would like it to be 13sp) should be respected. Hence the scale ratios aren't hard.
